#!/usr/bin/env python3
"""Regenerate INDEX.md (lab root) and 30_register/views/*.md from ideas.yaml.

ideas.yaml is the single source of truth; these outputs are derived. Never
hand-edit them. Run after any change to ideas.yaml (and after validate_ideas.py).
"""
import os
import sys

try:
    import yaml
except ImportError:
    sys.exit("FATAL: PyYAML not installed. `pip3 install pyyaml`.")

HERE = os.path.dirname(os.path.abspath(__file__))
REG = os.path.join(HERE, "..")            # 30_register/
ROOT = os.path.join(REG, "..")            # lab root
VIEWS = os.path.join(REG, "views")

NOVELTY_ORDER = [
    "genuinely-new", "flagged-unpursued", "adjacent-untested",
    "repo-killed", "repo-established",
]
PROBE_ORDER = {"trivial": 0, "cheap": 1, "moderate": 2, "heavy": 3}
LOCI = [
    "carries", "message-schedule", "round-function", "differential-trail",
    "state-cross-section", "feed-forward", "whole-function",
]
GEN = "<!-- GENERATED by 30_register/infra/rebuild_views.py — do not hand-edit. -->\n"


def esc(s):
    return str(s).replace("|", "\\|").replace("\n", " ")


def load():
    with open(os.path.join(REG, "ideas.yaml")) as f:
        return yaml.safe_load(f)


def row(e):
    return (f"| `{e['id']}` | {esc(e['one_liner'])} | {e['lens']} | "
            f"{e['novelty']} | {e['plausibility']} | {e['probe_cost']} | {e['status']} |")


HEAD = "| id | one-liner | lens | novelty | P | probe | status |\n|---|---|---|---|---|---|---|\n"


def write(path, text):
    with open(path, "w") as f:
        f.write(text)


def main():
    ideas = load()
    n = len(ideas)

    # INDEX.md — whole-lab scan, fresh angles first
    order = {nv: i for i, nv in enumerate(NOVELTY_ORDER)}
    s = sorted(ideas, key=lambda e: (order.get(e["novelty"], 9),
                                     -e["plausibility"],
                                     PROBE_ORDER.get(e["probe_cost"], 9)))
    out = [GEN, "# INDEX — whole-lab scan\n",
           f"_Generated from `30_register/ideas.yaml` ({n} entries). "
           "Fresh angles first. Rebuild: `python3 30_register/infra/rebuild_views.py`._\n",
           HEAD]
    out += [row(e) + "\n" for e in s]
    out += ["\nViews: [by novelty](30_register/views/by_novelty.md) · "
            "[by plausibility](30_register/views/by_plausibility.md) · "
            "[by locus](30_register/views/by_locus.md) · "
            "[shortlist](30_register/views/shortlist.md). "
            "Narrative footholds: [50_meta/shortlist.md](50_meta/shortlist.md).\n"]
    write(os.path.join(ROOT, "INDEX.md"), "".join(out))

    # by_novelty
    out = [GEN, "# Ideas by novelty\n"]
    for nv in NOVELTY_ORDER:
        grp = [e for e in ideas if e["novelty"] == nv]
        if not grp:
            continue
        grp.sort(key=lambda e: (-e["plausibility"], PROBE_ORDER.get(e["probe_cost"], 9)))
        out += [f"\n## {nv}  ({len(grp)})\n", HEAD] + [row(e) + "\n" for e in grp]
    write(os.path.join(VIEWS, "by_novelty.md"), "".join(out))

    # by_plausibility
    s = sorted(ideas, key=lambda e: (-e["plausibility"], PROBE_ORDER.get(e["probe_cost"], 9)))
    out = [GEN, "# Ideas by plausibility (desc), then cheapest probe first\n", HEAD]
    out += [row(e) + "\n" for e in s]
    write(os.path.join(VIEWS, "by_plausibility.md"), "".join(out))

    # by_locus
    out = [GEN, "# Ideas by locus (where in SHA-256 they act)\n"]
    for loc in LOCI:
        grp = [e for e in ideas if loc in (e.get("locus") or [])]
        if not grp:
            continue
        grp.sort(key=lambda e: (-e["plausibility"], PROBE_ORDER.get(e["probe_cost"], 9)))
        out += [f"\n## {loc}  ({len(grp)})\n", HEAD] + [row(e) + "\n" for e in grp]
    write(os.path.join(VIEWS, "by_locus.md"), "".join(out))

    # shortlist — live fresh angles only (the actionable triage)
    live_status = {"captured", "triaged", "deep-dive", "probe-designed", "probed"}
    fresh = {"genuinely-new", "flagged-unpursued", "adjacent-untested"}
    grp = [e for e in ideas if e["status"] in live_status and e["novelty"] in fresh]
    grp.sort(key=lambda e: (-e["plausibility"], PROBE_ORDER.get(e["probe_cost"], 9)))
    out = [GEN, "# Shortlist — live fresh angles (generated filter)\n",
           "_Status in {captured,triaged,deep-dive,probe-designed,probed} and a fresh novelty tier. "
           "Narrative version with skeptic notes: `50_meta/shortlist.md`._\n\n"]
    for e in grp:
        out.append(f"### `{e['id']}`  — P{e['plausibility']}, probe:{e['probe_cost']}, {e['status']}\n")
        out.append(f"- **{esc(e['title'])}**\n")
        out.append(f"- {esc(e['one_liner'])}\n")
        out.append(f"- lens: {e['lens']} · locus: {', '.join(e.get('locus') or [])}\n")
        out.append(f"- **dead if:** {esc(e['kill_criterion'])}\n")
        if e.get("dive"):
            out.append(f"- dive: `{e['dive']}`\n")
        out.append("\n")
    write(os.path.join(VIEWS, "shortlist.md"), "".join(out))

    print(f"Rebuilt INDEX.md + 4 views from {n} entries.")


if __name__ == "__main__":
    main()
