#!/usr/bin/env python3
"""
W2-QI2 — Message schedule as a stabilizer code -> trail weight = code distance.

Card claim: schedule parities = stabilizer generators; minimal trail weight = code
distance d(C); neutral moves = logical operators; carry = non-stabilizer perturbation.
Probe (N=4..12): build the GF(2) check matrix H for the first r rounds; low-weight-
codeword search for d(r); does d(r) JUMP near round 59? does the logical-operator count
track 256-132? **report the carry-gap (trail weight - d(C)), not just d(C)**.
Kill: dead if d(r) grows smoothly with NO jump near 59 and the logical count shows no
link to 132/256.

Construction (faithful to the card): the XOR-linearized SHA-256 message schedule
  W[i] = sigma1(W[i-2]) ^ W[i-7] ^ sigma0(W[i-15]) ^ W[i-16],  sigma GF(2)-linear,
is a linear recurrence. The code C(r) = { full schedule-difference vector [W[0..r-1]] :
the recurrence holds } is generated by the 16N free seed bits W[0..15]. We build its
generator matrix G(r) (each output schedule bit as a GF(2) linear function of the 16N
seed bits) and find d(r) = min nonzero codeword weight by information-set decoding
(Lee-Brickell, small p) -- exact-ish at the small N we use, with brute fallback.

The "carry-gap" = (true differential trail weight) - d(C): we estimate the true trail
weight as the minimum HAMMING weight of the MODULAR-add schedule difference realizing
the same seed difference (carries restored), minus the linear d(C). If the schedule were
purely linear the gap is 0; carries can only ADD weight, so gap>=0, and the card's
non-rebrand claim is gap = the QI1 magic budget.
"""
import sys, random, itertools
sys.path.insert(0, '/Users/mac/Desktop/sha256_theory_lab/wild_angles/probes/kernels')
import shabridge as sb

random.seed(20260603)

def make_lin(N):
    """GF(2)-linear sigma0/sigma1 as functions int->int at width N (scaled rotations)."""
    MASK = (1 << N) - 1
    def ror(x,r): r%=N; return ((x>>r)|(x<<(N-r)))&MASK
    def shr(x,r): return (x>>r)&MASK
    base = dict(s0=(7,18,3), s1=(17,19,10))
    sc = {k: tuple(max(0,min(N-1,round(a*N/32))) for a in t) for k,t in base.items()}
    def sig0(x): r=sc['s0']; return ror(x,r[0])^ror(x,r[1])^shr(x,r[2])
    def sig1(x): r=sc['s1']; return ror(x,r[0])^ror(x,r[1])^shr(x,r[2])
    return MASK, sig0, sig1

def gen_matrix(N, r):
    """Generator matrix of C(r): for each of the rN schedule output bits, its value as a
    GF(2) linear combination of the 16N seed bits, returned as a list of rN ints
    (bitmask over 16N seed columns). Built by linearity: response to each seed unit vector."""
    MASK, sig0, sig1 = make_lin(N)
    nseed = 16 * N
    # represent each schedule word W[i] as a list of N bitmasks over the 16N seed cols
    def build_W_from_seed(seedbits):
        # seedbits: list of 16 ints (each N bits) = a concrete seed; run linear recurrence
        W = list(seedbits) + [0]*(r-16 if r>16 else 0)
        for i in range(16, r):
            W.append(sig1(W[i-2]) ^ W[i-7] ^ sig0(W[i-15]) ^ W[i-16])
        return W[:r]
    rows = [0]*(r*N)  # row = output bit index (i*N+j), value = mask over seed cols
    for col in range(nseed):
        wi, bj = divmod(col, N)
        seed = [0]*16; seed[wi] = (1<<bj)
        W = build_W_from_seed(seed)
        for i in range(r):
            wbits = W[i]
            jj = 0
            while wbits:
                if wbits & 1:
                    rows[i*N + jj] |= (1 << col)
                wbits >>= 1; jj += 1
    return rows, nseed   # rows: rN masks over nseed cols (this is G^T actually: out-bit -> seed support)

def codeword_weight(rows, seedvec, nseed, r, N, start_bit=0):
    """Weight of codeword for a given seed bitmask, counting output bits from index
    start_bit onward (start_bit=16*N excludes the trivial seed words W[0..15])."""
    w = 0
    for k in range(start_bit, r*N):
        if bin(rows[k] & seedvec).count('1') & 1:
            w += 1
    return w

def min_distance(rows, nseed, r, N, isd_iters=4000, start_bit=0):
    """Min nonzero codeword weight (output bits counted from start_bit). For small nseed
    (<=18) brute (exact); else single/double seeds + low-weight ISD (upper bound)."""
    best = r*N + 1
    for i in range(nseed):
        w = codeword_weight(rows, 1<<i, nseed, r, N, start_bit)
        if 0 < w < best: best = w
    for i in range(nseed):
        for j in range(i+1, nseed):
            w = codeword_weight(rows, (1<<i)|(1<<j), nseed, r, N, start_bit)
            if 0 < w < best: best = w
    if nseed <= 18:
        for m in range(1, 1<<nseed):
            w = codeword_weight(rows, m, nseed, r, N, start_bit)
            if 0 < w < best: best = w
        return best, True
    for _ in range(isd_iters):
        p = random.randint(1,3)
        bits = random.sample(range(nseed), p)
        m = 0
        for b in bits: m |= (1<<b)
        w = codeword_weight(rows, m, nseed, r, N, start_bit)
        if 0 < w < best: best = w
    return best, False

def carry_gap(N, r, seedvec):
    """Realized trail weight with MODULAR-add schedule (carries restored) minus the
    XOR-linear weight, for a given seed difference vector. We instantiate a random base
    message, apply the seed difference, run BOTH the modular schedule and its XOR-lin
    version, and count HW of the expanded-word differences (W[16..r-1])."""
    MASK, sig0, sig1 = make_lin(N)
    o = make_lin(N)
    # modular schedule add
    def expand(seedwords, modular):
        W = list(seedwords)
        for i in range(16, r):
            if modular:
                W.append((sig1(W[i-2]) + W[i-7] + sig0(W[i-15]) + W[i-16]) & MASK)
            else:
                W.append(sig1(W[i-2]) ^ W[i-7] ^ sig0(W[i-15]) ^ W[i-16])
        return W
    # seedvec -> 16 seed words (N bits each)
    sw = [ (seedvec >> (i*N)) & MASK for i in range(16) ]
    rnd = random.Random(99)
    gaps = []
    for _ in range(8):
        base = [rnd.getrandbits(N) for _ in range(16)]
        b1 = base
        b2 = [ base[i] ^ sw[i] for i in range(16) ]
        Wm1 = expand(b1, True); Wm2 = expand(b2, True)
        Wx1 = expand(b1, False); Wx2 = expand(b2, False)
        wmod = sum(bin((Wm1[i]^Wm2[i]) & MASK).count('1') for i in range(16, r))
        wxor = sum(bin((Wx1[i]^Wx2[i]) & MASK).count('1') for i in range(16, r))
        gaps.append(wmod - wxor)
    return min(gaps), max(gaps)

if __name__ == '__main__':
    print("=== W2-QI2: schedule code distance d(r) vs round ===")
    print("    d_full = min wt over W[0..r-1]; d_exp = min wt over EXPANDED words W[16..r-1].")
    print("    Look for a JUMP near r=59; logical count vs 256-132=124; carry-gap=modular-XOR.\n")
    for N in (2, 3, 4):
        print(f"--- N={N} (seed dim 16N={16*N}) ---")
        ds_full = []; ds_exp = []
        for r in range(17, 33):   # need r>16 for expanded words to exist
            rows, nseed = gen_matrix(N, r)
            df, exf = min_distance(rows, nseed, r, N, start_bit=0)
            de, exe = min_distance(rows, nseed, r, N, start_bit=16*N)
            ds_full.append(df); ds_exp.append(de)
        print(f"  d_full(r) r=17..32: {ds_full}")
        print(f"  d_exp (r) r=17..32: {ds_exp}  (expanded-words-only; excludes trivial seed bits)")
        deltas = [ds_exp[i]-ds_exp[i-1] for i in range(1,len(ds_exp))]
        print(f"  d_exp deltas: {deltas}   max|jump|={max(abs(x) for x in deltas) if deltas else 0}")
        # carry gap on the min-weight expanded seed at r=32
        rows, nseed = gen_matrix(N, 32)
        # find a min-weight (expanded) seed
        bestm, bestw = None, 10**9
        cand = [1<<i for i in range(nseed)] + [(1<<i)|(1<<j) for i in range(nseed) for j in range(i+1,nseed)]
        for m in cand:
            w = codeword_weight(rows, m, nseed, 32, N, start_bit=16*N)
            if 0 < w < bestw: bestw, bestm = w, m
        gmin, gmax = carry_gap(N, 32, bestm) if bestm else (0,0)
        rk = sb.gf2_rank(rows, nseed)
        print(f"  rank(G@r=32)={rk} (logical count); 16N={16*N} vs 124. "
              f"carry-gap(min-wt seed)=[{gmin},{gmax}] (modular HW - XOR HW over W[16..31])\n")
