"""
W5-KR3 — Aperiodicity threshold: star-free (FO-definable) below 60, group-bearing at 61.

Card probe (verbatim, cheapest decidable form):
  N=2,3,4 build the syntactic monoid of L_r = {diff-sequences keeping da=0 through r};
  test x^{|M|} == x^{|M|+1} (aperiodic?) for r = 57..61; predict a clean True->False flip
  at 60->61, invariant across several base states.
Kill: non-aperiodic at r<=58, OR still aperiodic at 61, OR flickers per-message.

Krohn-Rhodes / Schuetzenberger background
-----------------------------------------
A finite monoid M is APERIODIC (group-free) iff x^k = x^{k+1} for some k, for every x
(equivalently: no nontrivial subgroup; equivalently the language is star-free / FO).
The card claims a clean flip APERIODIC (r<=60) -> GROUP-BEARING (r=61).

Faithful, cheap construction
----------------------------
For ONE fixed conditioning interior state (a "base state", as the card asks to vary), and
msgdiff fixed (cascade regime msgdiff=0), ONE SHA round is a deterministic automaton:
  state  = differential head (da, de)  (the tail lanes db..dh are forced by the
           shift-register structure, so the head is the whole free differential)
  letter = message word w in {0..2^N-1}  (path-2 word = w + msgdiff)
  delta((da,de), w) -> (da', de') = round-differential output.
The TRANSITION MONOID of round r is the submonoid of maps on the head-state set generated by
the letter-actions { sigma_w : head -> delta(head, w) }.  Its aperiodicity == star-freeness
of the language recognized by this automaton (Schuetzenberger).  We:
  1. enumerate the reachable head set,
  2. build one generator per word w (a TOTAL map on heads),
  3. close under composition to the transition monoid (hard cap -> INCONCLUSIVE if blown),
  4. test aperiodicity by detecting any element whose functional period > 1.

The decisive comparison: the round OPERATION is identical for r=57..61 -- the ONLY thing
that changes is K[r] (a constant added inside the adder).  So we run the SAME construction
with k = K[r] & mask for r=57..61 (and several base states) and ask whether aperiodicity
actually depends on the round index, or is constant (a smooth/round-invariant property).
A genuine 60->61 flip would require K[61]'s value to inject a cyclic subgroup that K[57..60]
do not.
"""
import sys, random
sys.path.insert(0, '/Users/mac/Desktop/sha256_theory_lab/wild_angles/probes/kernels')
import shabridge as sb
import transfer_operator as to

s = sb.s
MASKN = lambda N: (1 << N) - 1


def transition_monoid(N, k, base_state, msgdiff=0, head_cap=64, monoid_cap=20000):
    """Build the transition monoid of one SHA round (fixed conditioning base_state, fixed
    msgdiff) on the differential-head automaton; return aperiodicity + sizes.

    Returns dict(aperiodic, monoid_size, n_states, capped(bool), max_period).
    """
    rnd = to._make_round(N)
    m = MASKN(N)
    cs = list(base_state)

    def delta(head, w):
        da, de = head
        st1 = list(cs)
        st2 = list(cs)
        st2[0] = (st2[0] + da) & m
        st2[4] = (st2[4] + de) & m
        o1 = rnd(st1, k, w)
        o2 = rnd(st2, k, (w + msgdiff) & m)
        return ((o2[0] - o1[0]) & m, (o2[4] - o1[4]) & m)

    words = list(range(1 << N))  # N tiny => full alphabet
    # 1) reachable head set
    seeds = [(0, 0), (1, 0), (0, 1)]
    if N >= 2:
        seeds += [(1 << (N - 1), 0), (0, 1 << (N - 1))]
    states = set(seeds)
    frontier = list(seeds)
    while frontier:
        new = set()
        for h in frontier:
            for w in words:
                h2 = delta(h, w)
                if h2 not in states:
                    new.add(h2)
        if not new or len(states) > head_cap:
            break
        states |= new
        frontier = list(new)
    states = sorted(states)
    if len(states) > head_cap:
        return dict(aperiodic=None, monoid_size=None, n_states=len(states),
                    capped=True, max_period=None)
    idx = {h: i for i, h in enumerate(states)}
    n = len(states)

    # 2) generators: total map per word (out-of-set image -> fix, a completion that cannot
    #    create or destroy a nontrivial subgroup on the recurrent part).
    def gen_for(w):
        return tuple(idx.get(delta(h, w), idx[h]) for h in states)

    gens = sorted({gen_for(w) for w in words})

    # 3) close under composition (a then b): r[i] = b[a[i]]
    def compose(a, b):
        return tuple(b[a[i]] for i in range(n))

    ident = tuple(range(n))
    M = {ident, *gens}
    frontier = list(M)
    capped = False
    while frontier:
        nxt = []
        for x in frontier:
            for g in gens:
                y = compose(x, g)
                if y not in M:
                    M.add(y)
                    nxt.append(y)
                    if len(M) > monoid_cap:
                        capped = True
                        break
            if capped:
                break
        if capped:
            break
        frontier = nxt
    if capped:
        return dict(aperiodic=None, monoid_size=len(M), n_states=n, capped=True,
                    max_period=None)

    # 4) aperiodicity: detect any element with functional period > 1 (a group element)
    max_period = 1
    aperiodic = True
    for x in M:
        seen = {}
        cur = x
        i = 0
        while cur not in seen:
            seen[cur] = i
            cur = compose(cur, x)
            i += 1
        period = i - seen[cur]
        if period > 1:
            aperiodic = False
            if period > max_period:
                max_period = period
    return dict(aperiodic=aperiodic, monoid_size=len(M), n_states=n, capped=False,
                max_period=max_period)


if __name__ == '__main__':
    print("W5-KR3  aperiodicity of the da=0 transition monoid, per round r=57..61")
    print("round OPERATION is identical every round; only K[r] (added in-adder) changes.\n")
    rng = random.Random(7)
    for N in (2, 3):
        print(f"================ N={N} ================")
        n_base = 4
        base_states = [[rng.getrandbits(N) for _ in range(8)] for _ in range(n_base)]
        for r in range(57, 62):
            k = s.K[r] & MASKN(N)
            verdicts = []
            sizes = []
            states_n = []
            for bs in base_states:
                res = transition_monoid(N, k, bs, msgdiff=0)
                verdicts.append(res['aperiodic'])
                sizes.append(res['monoid_size'])
                states_n.append(res['n_states'])
            # collapse across base states
            if all(v is True for v in verdicts):
                tag = "APERIODIC (all bases)"
            elif all(v is False for v in verdicts):
                tag = "GROUP-BEARING (all bases)"
            elif any(v is None for v in verdicts):
                tag = f"INCONCLUSIVE/capped {verdicts}"
            else:
                tag = f"FLICKERS per-base {verdicts}"
            print(f"  r={r}  K[{r}]&mask={k:>3}  |M|~{sizes}  states~{states_n}  -> {tag}")
        print()
