"""
W5-KR2 — Holonomy decomposition: de58's power-of-2 image is a cyclic-group order.

Card probe (verbatim):
  build the N-bit adder carry monoid, compute holonomy group factors (cyclic?); cross-check
  de58 image = product of holonomy orders along the de58 add-path, and candidate-image
  disjointness = coset structure on the N=32 sweep data.
Kill: holonomy groups non-cyclic at N>=6, OR de58 image not a power of 2 at N=8..14.

Claim: the carry monoid's holonomy groups are tiny/cyclic; de58 is the unique register with
nontrivial (Z/2^k) holonomy, k = log2|de58|, EXPLAINING the measured 2^hw(db56) law.

The decisive question (prior finding #6)
----------------------------------------
The 2^hw(db56) law for |de58| is ALREADY established ground truth (it is a Maj/AND image
COUNT).  KR2 is a CONFIRMED only if the holonomy decomposition DERIVES the exponent
hw(db56) from a GROUP order -- otherwise it is a restate of a known number.  So we must
test the *mechanism*, not just re-observe the power of 2.

We build the binary-addition carry monoid and ask: are its holonomy / maximal-subgroup
factors nontrivial cyclic groups (Z/2^k) whose ORDERS could equal |de58|?  Krohn-Rhodes of
integer addition is the textbook flip-flop case; we verify computationally whether the carry
monoid is APERIODIC (group-free, holonomy trivial) or carries a real Z/2^k.

Part A: carry transformation monoid of the N-bit ripple adder.
  Carry state c in {0,1}.  Each input-bit pair (x_i,y_i) induces a carry-map:
     (0,0) -> KILL      : c |-> 0           (constant 0)
     (1,1) -> GENERATE  : c |-> 1           (constant 1)
     (0,1),(1,0) -> PROP : c |-> c          (identity)
  The monoid generated by {KILL, GEN, PROP=id} on {0,1}.  Compute |M|, and its maximal
  subgroups (group H-classes) / any element of functional period > 1.  Group-free <=> the
  largest period is 1.

Part B: does the holonomy supply 2^hw(db56)?
  Compose N copies (one per bit) -- the full add carry monoid is still on the 1-bit carry
  state, so its monoid is the SAME 3-element {0,1,id}.  Its maximal subgroup order is 1.
  We then check whether 2^hw equals ANY product of holonomy (group) orders: with all group
  orders = 1, the only product is 1, NOT 2^hw.  We report hw(db56) for N=8..14 (= the real
  de58 exponent) and confirm it is NOT a holonomy-group order.

Part C: where 2^hw actually comes from (counting, not a group).  de58 = #{ images of the
  Maj/db carry map } = 2^(#free bits) = 2^hw(db56): an IMAGE COUNT, abelian-free.
"""
import sys, math
sys.path.insert(0, '/Users/mac/Desktop/sha256_theory_lab/wild_angles/probes/kernels')
import shabridge as sb

s = sb.s

# Part A -- the binary-addition carry monoid on the 1-bit carry state {0,1}
KILL = (0, 0)   # c -> 0   (maps state 0->0, 1->0)   tuple indexed by current carry
GEN  = (1, 1)   # c -> 1
PROP = (0, 1)   # c -> c   (identity)


def compose(a, b):
    # (a then b): result[c] = b[a[c]]
    return tuple(b[a[c]] for c in range(len(a)))


def close_monoid(gens):
    ident = (0, 1)
    M = {ident, *gens}
    frontier = list(M)
    while frontier:
        nxt = []
        for x in frontier:
            for g in gens:
                y = compose(x, g)
                if y not in M:
                    M.add(y)
                    nxt.append(y)
        frontier = nxt
    return M


def max_period(M):
    mp = 1
    for x in M:
        seen, cur, i = {}, x, 0
        while cur not in seen:
            seen[cur] = i
            cur = compose(cur, x)
            i += 1
        mp = max(mp, i - seen[cur])
    return mp


def maximal_subgroup_orders(M):
    """For each idempotent e in M (e*e=e), the maximal subgroup at e = the H-class of e =
    {x in M : x*e=x=e*x and x has an inverse in eMe}. For this 2-element-state monoid we
    just report, per idempotent, the size of the group of units of e*M*e."""
    idems = [e for e in M if compose(e, e) == e]
    orders = []
    for e in idems:
        eMe = {compose(compose(e, x), e) for x in M}
        # units: elements g in eMe with an inverse h in eMe, g*h = e = h*g
        units = set()
        for g in eMe:
            for h in eMe:
                if compose(g, h) == e and compose(h, g) == e:
                    units.add(g)
                    break
        orders.append((e, len(units)))
    return orders


if __name__ == '__main__':
    print("W5-KR2  does the carry-monoid holonomy DERIVE de58's 2^hw(db56), or merely restate it?\n")

    print("Part A: binary-addition carry monoid on the 1-bit carry state")
    gens = [KILL, GEN, PROP]
    M = close_monoid(gens)
    mp = max_period(M)
    print(f"  generators: KILL={KILL}, GENERATE={GEN}, PROP/id={PROP}")
    print(f"  |carry monoid| = {len(M)}   elements = {sorted(M)}")
    print(f"  max functional period over the monoid = {mp}  "
          f"-> {'APERIODIC (group-free)' if mp == 1 else 'GROUP-BEARING'}")
    subs = maximal_subgroup_orders(M)
    print(f"  maximal-subgroup (holonomy group) orders per idempotent: "
          f"{[o for (_, o) in subs]}  (all 1 => trivial holonomy, NOT cyclic Z/2^k)")
    holonomy_nontrivial = any(o > 1 for (_, o) in subs)
    print(f"  any nontrivial holonomy group? {holonomy_nontrivial}\n")

    print("Part B: does any product of holonomy-group orders equal |de58| = 2^hw(db56)?")
    print("  (all holonomy orders are 1, so every product is 1)")
    de = sb.DE_SIZES
    print("  N   hw(db56)   |de58|=2^hw   product-of-holonomy-orders   derived-by-holonomy?")
    derived_any = False
    for N in (8, 10, 11, 12, 13, 14):
        de58 = de[N][1]
        hw = int(round(math.log2(de58)))
        prod_holo = 1  # product of trivial holonomy group orders
        derived = (prod_holo == de58)
        derived_any = derived_any or derived
        powof2 = (de58 & (de58 - 1)) == 0
        print(f"  {N:<3} {hw:<10} {de58:<13} {prod_holo:<27} {derived}   "
              f"(de58 power-of-2? {powof2})")
    print()

    print("Part C: where 2^hw actually comes from")
    print("  de58 = #{distinct carry/Maj images} = 2^(free image bits) = 2^hw(db56):")
    print("  an IMAGE COUNT of an aperiodic (group-free) Maj/AND map -- NOT a Z/2^k group order.")
    print(f"\n  >>> KILL: holonomy non-cyclic at N>=6? "
          f"{'no -- trivial (group-free)' }   "
          f"de58 not a power of 2 at N=8..14? no (always 2^hw)")
    print(f"  >>> CONFIRMED requires holonomy to DERIVE hw(db56) from a group order: "
          f"derived_any = {derived_any}  (it does NOT; holonomy is trivial)")
