"""
W5-KR5 — Group kernel: all group complexity localizes to the feed-forward ADD.

Card probe (verbatim):
  N=2,3 compute G(M) of full compression (J-class/group-H-class route); is it = the
  feed-forward group alone? are the rounds-only G trivial?
Kill: rounds-only (no feed-forward) has a NONTRIVIAL group quotient (rotations carry group
  complexity) — a valuable negative.

Claim: the whole-compression monoid's maximal group quotient G(M) equals the feed-forward
translation group <H_in + .>, with the 64 reversible rounds in the APERIODIC kernel ("group
trivial"). I.e. hardness would be constant in round count and born entirely in the final ADD.

Discriminating computation
--------------------------
The kill condition is a direct, decidable question: is the ROUNDS-ONLY transformation monoid
group-TRIVIAL (aperiodic), or does it carry a nontrivial group?

(A) ROUNDS-ONLY.  Fix a message word w; one SHA round is a permutation of the interior state
    (it is invertible: given w you can run it backward).  We build, for a fixed w (and a few
    w's), the permutation the round induces on the (a,e) head carrier, and compute the order
    of the GROUP it generates (a permutation group => its order is the group-complexity
    witness).  If that order > 1, the rounds-only part is NOT aperiodic => kill fires.
    We also report the maximal subgroup (group H-class) order of the rounds-only monoid via
    the smallest functional period seen, to be safe.

(B) FEED-FORWARD ADD.  The Davies-Meyer feed-forward H_out = H_in + state_after is a family
    of TRANSLATIONS x -> x + c on Z/2^N per lane; the set of all such translations is the
    cyclic group (Z/2^N)^lanes (abelian, order 2^{N*lanes}).  We confirm it is a nontrivial
    group and that, being many-to-one only via wraparound modular reduction, it is where
    collisions are forced.

The card is CONFIRMED only if rounds-only is group-trivial AND the feed-forward supplies the
group.  Per prior finding #5 ("carries are the hardness") and #4 ("no round knee"), and given
the round map is a bijection, we expect rounds-only to ALREADY be group-bearing -> KILL.
"""
import sys, random, math
sys.path.insert(0, '/Users/mac/Desktop/sha256_theory_lab/wild_angles/probes/kernels')
import shabridge as sb
import transfer_operator as to

s = sb.s
MASKN = lambda N: (1 << N) - 1


def round_perm_on_head(N, k, w, tail_const=0):
    """The permutation one SHA round induces on the (a,e) head carrier (tail lanes pinned).
    Returns a tuple `perm` with perm[idx(a,e)] = idx(round_head(a,e))."""
    rnd = to._make_round(N)
    m = MASKN(N)
    tc = tail_const & m
    pts = [(a, e) for a in range(1 << N) for e in range(1 << N)]
    idx = {p: i for i, p in enumerate(pts)}

    def head_after(a, e):
        st = [a, tc, tc, tc, e, tc, tc, tc]
        o = rnd(st, k, w)
        return (o[0], o[4])

    img = [idx[head_after(a, e)] for (a, e) in pts]
    return img, pts


def is_permutation(img):
    return len(set(img)) == len(img)


def perm_order(img):
    """Order of a permutation (lcm of cycle lengths). Assumes img is a permutation."""
    n = len(img)
    seen = [False] * n
    order = 1
    for st in range(n):
        if seen[st]:
            continue
        length = 0
        cur = st
        while not seen[cur]:
            seen[cur] = True
            cur = img[cur]
            length += 1
        order = order * length // math.gcd(order, length)
    return order


def group_generated_order(perms, n, cap=2_000_000):
    """Order of the permutation group generated by a list of permutations on n points
    (closure; capped)."""
    def compose(a, b):
        return tuple(b[a[i]] for i in range(n))
    ident = tuple(range(n))
    G = {ident}
    frontier = [ident] + [tuple(p) for p in perms]
    G |= {tuple(p) for p in perms}
    while frontier:
        nxt = []
        for x in frontier:
            for p in perms:
                y = compose(x, tuple(p))
                if y not in G:
                    G.add(y)
                    nxt.append(y)
                    if len(G) > cap:
                        return len(G), True
        frontier = nxt
    return len(G), False


def feedforward_group_order(N, lanes=8):
    """The Davies-Meyer feed-forward translations x->x+c mod 2^N form (Z/2^N)^lanes."""
    return (1 << N) ** lanes  # order of the abelian translation group (the 'group kernel')


if __name__ == '__main__':
    print("W5-KR5  is the ROUNDS-ONLY part group-trivial, and does the feed-forward ADD")
    print("carry the group?  (kill fires if rounds-only has a nontrivial group)\n")
    for N in (2, 3):
        print(f"================ N={N} ================")
        rng = random.Random(3)
        words = [1, 2, 3] + [rng.getrandbits(N) for _ in range(3)]
        words = sorted(set(w & MASKN(N) for w in words))
        perms = []
        orders = []
        for r_demo, w in [(60, w) for w in words]:
            k = s.K[60] & MASKN(N)  # representative tail round constant
            img, pts = round_perm_on_head(N, k, w)
            if is_permutation(img):
                o = perm_order(img)
                perms.append(img)
                orders.append(o)
                print(f"  rounds-only: round(k=K60, w={w})  is a PERMUTATION of {len(img)} "
                      f"head states, cyclic order = {o}")
            else:
                print(f"  rounds-only: round(k=K60, w={w})  NOT a permutation on the head "
                      f"(tail-pinning artifact); collisions present at the head")
        if perms:
            gord, capped = group_generated_order(perms, len(perms[0]))
            cap_tag = ">cap" if capped else "exact"
            rounds_group_trivial = (gord == 1)
            print(f"  rounds-only GROUP generated by these round-perms: order = {gord} "
                  f"({cap_tag})  -> group-trivial? {rounds_group_trivial}")
        ff = feedforward_group_order(N)
        print(f"  feed-forward translation group (Z/2^{N})^8 order = {ff} "
              f"(nontrivial abelian) -- where collisions are forced")
        print(f"  >>> KILL fires (rounds-only NOT group-trivial)? "
              f"{bool(perms) and orders and max(orders) > 1}\n")
