"""
W5-KR1 — Group-complexity jump: the wall is a +1 in the Eilenberg (group-complexity) hierarchy.

Card probe (verbatim):
  N=2,3 build the round transformation monoid over all W[r]; first round with a nontrivial
  idempotent-power element (a group element)? predict r=61.
Kill: group element appears at r<=58.

NOT the carry-automaton: this is "which FUNCTIONS are realizable by composition" (a
divisor/quotient algebra invariant), not state reachability.

Construction
------------
At round r the round map is  f_{r,w}(state) = SHA_round(state, K[r], w)  acting on the FULL
8-word interior state (each word N bits) -- but the full state space is 2^{8N}, far too big to
enumerate.  We follow the card's intent ("the round transformation monoid") on the smallest
faithful carrier that still exposes group structure: the (a,e) HEAD pair, which the
shift-register structure makes the only non-shifted lanes (b'=a, c'=b, d'=c, f'=e, g'=f, h'=g
are forced; only a' and e' are computed).  We fix the carried tail lanes to a representative
constant and let the round act on (a,e) in F_2^N x F_2^N.  Generators = { f_{r,w} } over all
message words w (the "over all W[r]" in the card).  We build the monoid by closure and detect
the FIRST round index r whose generator-set contains, or whose monoid contains, a NONTRIVIAL
GROUP ELEMENT (an element x with x^k = x^{2k}, x^k != identity-on-its-image, period>1).

KEY ADVERSARIAL POINT (prior finding #4): the round OPERATION is identical for every r; only
K[r] changes.  So we MEASURE group-presence per round r=55..63 and ask whether the first
group element really first appears at 61, or appears early/everywhere (which would mean the
"+1 at the wall" is bookkeeping, not a round-specific jump).  Because K is just an additive
constant inside the adder, we expect NO round index to be special.
"""
import sys, random, itertools
sys.path.insert(0, '/Users/mac/Desktop/sha256_theory_lab/wild_angles/probes/kernels')
import shabridge as sb
import transfer_operator as to

s = sb.s
MASKN = lambda N: (1 << N) - 1


def round_head_monoid(N, k, tail_const=0, state_cap=256, monoid_cap=200000):
    """Transformation monoid generated by { (a,e) -> round head } over all words w, at one
    round constant k.  Carrier = (a,e) in [0,2^N)^2 (full, since N tiny).  Tail lanes
    b,c,d,f,g,h fixed to tail_const.  Returns dict with aperiodicity + group info.
    """
    rnd = to._make_round(N)
    m = MASKN(N)
    tc = tail_const & m

    # carrier = all (a,e) pairs
    pts = [(a, e) for a in range(1 << N) for e in range(1 << N)]
    if len(pts) > state_cap:
        return dict(has_group=None, monoid_size=None, n_states=len(pts), capped=True,
                    max_period=None)
    idx = {p: i for i, p in enumerate(pts)}
    n = len(pts)

    def head_after(a, e, w):
        st = [a, tc, tc, tc, e, tc, tc, tc]
        o = rnd(st, k, w)
        return (o[0], o[4])

    words = list(range(1 << N))

    def gen_for(w):
        return tuple(idx[head_after(a, e, w)] for (a, e) in pts)

    gens = sorted({gen_for(w) for w in words})

    def compose(a, b):
        return tuple(b[a[i]] for i in range(n))

    ident = tuple(range(n))
    M = {ident, *gens}
    frontier = list(M)
    capped = False
    while frontier:
        nxt = []
        for x in frontier:
            for g in gens:
                y = compose(x, g)
                if y not in M:
                    M.add(y)
                    nxt.append(y)
                    if len(M) > monoid_cap:
                        capped = True
                        break
            if capped:
                break
        if capped:
            break
        frontier = nxt
    if capped:
        return dict(has_group=None, monoid_size=len(M), n_states=n, capped=True,
                    max_period=None)

    # group element: any element with functional period > 1
    max_period = 1
    has_group = False
    for x in M:
        seen = {}
        cur = x
        i = 0
        while cur not in seen:
            seen[cur] = i
            cur = compose(cur, x)
            i += 1
        period = i - seen[cur]
        if period > 1:
            has_group = True
            if period > max_period:
                max_period = period
    return dict(has_group=has_group, monoid_size=len(M), n_states=n, capped=False,
                max_period=max_period)


if __name__ == '__main__':
    print("W5-KR1  first round whose transformation monoid has a nontrivial GROUP element")
    print("(round operation identical every round; only K[r] differs)\n")
    for N in (2, 3):
        print(f"================ N={N} ================")
        first_group = None
        for r in range(55, 64):
            k = s.K[r] & MASKN(N)
            res = round_head_monoid(N, k)
            if res['capped']:
                tag = f"CAPPED |M|>{res['monoid_size']}"
            elif res['has_group']:
                tag = f"GROUP (max_period={res['max_period']})"
                if first_group is None:
                    first_group = r
            else:
                tag = "aperiodic (no group)"
            print(f"  r={r}  K[{r}]&mask={k:>3}  |M|={res['monoid_size']:>6} "
                  f"states={res['n_states']:>3}  -> {tag}")
        print(f"  >>> first round with a group element: {first_group} "
              f"(card predicts 61; kill if <=58)\n")
