"""
W5-KR4 — Wreath-length / first group factor: the hard part is one localized group gate.

Card probe (verbatim):
  N=2 build T_r tables, holonomy-coordinatize (or the Green's-relations group-J-class lower
  bound); does gamma(r) jump 0->1 at 61?  does m relate to 2^-2N?
Kill: gamma>=1 at r<=59, OR gamma(61)=0, OR m a huge prime.
(moderate cost -> N tiny; INCONCLUSIVE rather than blow up.)

Claim: KR coordinatizes the tail map into a flip-flop cascade with the FIRST group factor at
round 61, top level, order m (~4 = two conditions x 2): a constructive circuit whose one
group gate is the precise hard part.

gamma(r) lower bound (decidable, cheap)
---------------------------------------
gamma(r) = Krohn-Rhodes group complexity (# of group levels) of the transformation monoid of
the ACCUMULATED tail transform T_r (the round maps composed from a start round up to r).
A clean, computable LOWER BOUND: gamma(r) >= 1  iff  the monoid of T_r contains a NONTRIVIAL
maximal subgroup (a group H-class), equivalently a nontrivial group element (functional period
> 1).  (Group complexity >= 1 exactly when the monoid is non-aperiodic.)  We compute, per round
r, the largest functional period m(r) of any element of the accumulated-tail monoid on the
(a,e) head carrier, and read gamma(r) >= 1 <=> m(r) > 1.

We build T_r as the transformation monoid generated by the round-r head maps over a few words,
ACCUMULATED with the prior rounds (we compose the monoids of rounds start..r).  Because each
round is the same operation, we expect m(r) > 1 (a group) for ALL r including r<=59, which
fires the kill, and m to NOT be ~4 nor a single localized top gate.
"""
import sys, random, math
sys.path.insert(0, '/Users/mac/Desktop/sha256_theory_lab/wild_angles/probes/kernels')
import shabridge as sb
import transfer_operator as to

s = sb.s
MASKN = lambda N: (1 << N) - 1


def head_gens(N, k, words, tail_const=0):
    """Generators (total maps on the (a,e) head carrier) for one round with constant k."""
    rnd = to._make_round(N)
    m = MASKN(N)
    tc = tail_const & m
    pts = [(a, e) for a in range(1 << N) for e in range(1 << N)]
    idx = {p: i for i, p in enumerate(pts)}
    n = len(pts)

    def head_after(a, e, w):
        st = [a, tc, tc, tc, e, tc, tc, tc]
        o = rnd(st, k, w)
        return (o[0], o[4])

    gens = sorted({tuple(idx[head_after(a, e, w)] for (a, e) in pts) for w in words})
    return gens, n


def monoid_max_period(gens_list, n, cap=300000):
    """Close the monoid generated by ALL gens in gens_list (an accumulated multi-round
    generator pool) and return (monoid_size, max_functional_period, capped)."""
    def compose(a, b):
        return tuple(b[a[i]] for i in range(n))
    ident = tuple(range(n))
    gens = []
    seen_g = set()
    for g in gens_list:
        if g not in seen_g:
            seen_g.add(g)
            gens.append(g)
    M = {ident, *gens}
    frontier = list(M)
    capped = False
    while frontier:
        nxt = []
        for x in frontier:
            for g in gens:
                y = compose(x, g)
                if y not in M:
                    M.add(y)
                    nxt.append(y)
                    if len(M) > cap:
                        capped = True
                        break
            if capped:
                break
        if capped:
            break
        frontier = nxt
    max_period = 1
    for x in M:
        seen = {}
        cur = x
        i = 0
        while cur not in seen:
            seen[cur] = i
            cur = compose(cur, x)
            i += 1
        period = i - seen[cur]
        if period > max_period:
            max_period = period
    return len(M), max_period, capped


if __name__ == '__main__':
    print("W5-KR4  gamma(r) >= 1 (group factor present) for the ACCUMULATED tail transform T_r")
    print("(group complexity >= 1  <=>  monoid non-aperiodic  <=>  max functional period > 1)\n")
    N = 2
    print(f"================ N={N} (tiny, moderate-cost card) ================")
    rng = random.Random(11)
    words = sorted(set([0, 1, 2, 3]))  # full alphabet at N=2
    # accumulate from a start round; report gamma(r) for r = 55..63
    START = 55
    accum_gens = []
    for r in range(START, 64):
        k = s.K[r] & MASKN(N)
        g, n = head_gens(N, k, words)
        accum_gens.extend(g)
        msize, mper, capped = monoid_max_period(accum_gens, n)
        gamma_ge1 = mper > 1
        cap_tag = " (CAPPED)" if capped else ""
        print(f"  T_{r}: accumulated rounds {START}..{r}  |M|={msize}{cap_tag}  "
              f"max_period m={mper}  -> gamma(r)>=1 ? {gamma_ge1}")
    print()
    # also the SINGLE-round group factor m at r=61 vs r=59 (is r=61 special? is m~4?)
    print("  Per-single-round group factor m(r) (NOT accumulated) — is r=61 special / m~4?")
    for r in (58, 59, 60, 61, 62):
        k = s.K[r] & MASKN(N)
        g, n = head_gens(N, k, words)
        msize, mper, capped = monoid_max_period(g, n)
        print(f"    r={r}: single-round monoid |M|={msize}  max_period m={mper}")
    print("\n  card predicts gamma jumps 0->1 at 61 with m~4; "
          "kill if gamma>=1 at r<=59, or gamma(61)=0, or m a huge prime.")
